# Generated by Django 2.0.8 on 2019-01-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuntuacionLicorFormulario',
            new_name='PuntuacionCategoriaLicor',
        ),
        migrations.RenameModel(
            old_name='PuntuacionesMarcaLicor',
            new_name='PuntuacionMarcaLicor',
        ),
        migrations.RenameModel(
            old_name='PuntuacionesOrigenLicor',
            new_name='PuntuacionOrigenLicor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='formulario',
            name='graduacionMaxima',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='graduacionMinima',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
